konsumentgrensesnitt:
 image: "fint/ansatt-konsumentgrensesnitt-poc"
 ports:
  - "8080:8080"

konsumentgrensesnitt-mock:
 image: "fint/ansatt-konsumentgrensesnitt-poc"
 ports:
  - "8081:8080"
 environment:
  spring.profiles.active: mock

rabbitmq:
  hostname: "rabbitmq-poc"
  image: "rabbitmq:3-management"
  ports:
   - "15672:15672"
   - "5672:5672"
  environment:
   RABBITMQ_DEFAULT_USER: "guest"
   RABBITMQ_DEFAULT_PASS: "guest"

